# Generated by Django 4.2.4 on 2023-09-03 10:55

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=service.models.category_icon_upload_path,
            ),
        ),
    ]
