# Generated by Django 4.2.4 on 2023-09-03 11:37

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=service.models.service_banner_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=service.models.service_icon_upload_path
            ),
        ),
    ]
